kind: pipeline
name: default

trigger:
  event:
    exclude:
      - pull_request

steps:
#- name: shellcheck
#  image: koalaman/shellcheck-alpine
#  pull: always
#  commands:
#    - shellcheck --version
#    - for file in $(find ./root -type f); do echo $file; shellcheck $file; done;

- name: dev-build
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: vertigo235/nugsalert
    tags: 
        - '${DRONE_BRANCH}'
        - '${DRONE_BRANCH}-${DRONE_COMMIT:0:6}'
    cache_from: vertigo235/nugsalert
  when:
    branch:
      exclude:
        - master
    event:
      - push
    
- name: build
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: vertigo235/nugsalert
    tags:
      - latest
      - '1'
      - '1.0'
      - '1.0.${DRONE_BUILD_NUMBER}'
  when:
    branch:
      - master